# Generated by Django 5.0.4 on 2024-04-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_owner_usersettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='minimal_spends_for_notifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='minimal_spends_on_model_for_notifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='time_between_entering_for_notifications',
            field=models.IntegerField(default=0),
        ),
    ]
