# Generated by Django 5.0.4 on 2024-04-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_usersettings_minimal_spends_for_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='minimal_spends_for_notifications',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='time_between_entering_for_notifications',
            field=models.IntegerField(default=5),
        ),
    ]
