# Generated by Django 5.0.4 on 2024-04-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='license',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
