# Generated by Django 5.0.4 on 2024-04-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollerprocess',
            name='pid',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
