# Generated by Django 5.0.4 on 2024-04-20 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('event_type', models.CharField(choices=[('broadcastStart', 'Broadcast Start'), ('broadcastStop', 'Broadcast Stop'), ('fanclubJoin', 'Fan Club Join'), ('follow', 'Follow'), ('mediaPurchase', 'Media Purchase'), ('tip', 'Tip')], max_length=20)),
                ('received_at', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.member')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.model')),
            ],
        ),
    ]
