# Generated by Django 5.0.4 on 2024-04-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_has_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_license',
        ),
    ]
